"""empty message

Revision ID: 3cf2c08437ce
Revises: 6fbecaf44840
Create Date: 2021-04-24 15:55:33.902651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cf2c08437ce'
down_revision = '6fbecaf44840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profession_table')
    op.drop_table('profession')
    op.add_column('raider', sa.Column('has_cooking', sa.Boolean(), nullable=True))
    op.add_column('raider', sa.Column('has_first_aid', sa.Boolean(), nullable=True))
    op.add_column('raider', sa.Column('has_fishing', sa.Boolean(), nullable=True))
    op.add_column('raider', sa.Column('profession1', sa.String(length=64), nullable=True))
    op.add_column('raider', sa.Column('profession2', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raider', 'profession2')
    op.drop_column('raider', 'profession1')
    op.drop_column('raider', 'has_fishing')
    op.drop_column('raider', 'has_first_aid')
    op.drop_column('raider', 'has_cooking')
    op.create_table('profession',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('profession_table',
    sa.Column('raider_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('profession_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], name='profession_table_ibfk_1'),
    sa.ForeignKeyConstraint(['raider_id'], ['raider.id'], name='profession_table_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
