"""empty message

Revision ID: 4dc7f8b9f106
Revises: a6d10d1ea68a
Create Date: 2021-04-24 11:12:15.284964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc7f8b9f106'
down_revision = 'a6d10d1ea68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profession', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profession', 'name')
    # ### end Alembic commands ###
