"""empty message

Revision ID: 4e0895c8868f
Revises: d7d0aff6de67
Create Date: 2021-04-24 10:41:58.308259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0895c8868f'
down_revision = 'd7d0aff6de67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_table',
    sa.Column('left_friend_id', sa.Integer(), nullable=False),
    sa.Column('right_friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_friend_id'], ['raider.id'], ),
    sa.ForeignKeyConstraint(['right_friend_id'], ['raider.id'], ),
    sa.PrimaryKeyConstraint('left_friend_id', 'right_friend_id')
    )
    op.create_table('profession_table',
    sa.Column('raider_id', sa.Integer(), nullable=True),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ),
    sa.ForeignKeyConstraint(['raider_id'], ['raider.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profession_table')
    op.drop_table('friend_table')
    # ### end Alembic commands ###
