"""empty message

Revision ID: 6fbecaf44840
Revises: fb579f86406a
Create Date: 2021-04-24 13:52:30.070690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fbecaf44840'
down_revision = 'fb579f86406a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_table',
    sa.Column('left_partner_id', sa.Integer(), nullable=False),
    sa.Column('right_partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_partner_id'], ['raider.id'], ),
    sa.ForeignKeyConstraint(['right_partner_id'], ['raider.id'], ),
    sa.PrimaryKeyConstraint('left_partner_id', 'right_partner_id')
    )
    op.drop_constraint('raider_ibfk_1', 'raider', type_='foreignkey')
    op.drop_column('raider', 'partner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raider', sa.Column('partner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('raider_ibfk_1', 'raider', 'raider', ['partner_id'], ['id'])
    op.drop_table('partner_table')
    # ### end Alembic commands ###
