"""empty message

Revision ID: 8134a3bb39b4
Revises: 4dc7f8b9f106
Create Date: 2021-04-24 11:22:38.694211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8134a3bb39b4'
down_revision = '4dc7f8b9f106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raider', sa.Column('is_main', sa.Boolean(), nullable=True))
    op.add_column('raider', sa.Column('is_raid_leader', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raider', 'is_raid_leader')
    op.drop_column('raider', 'is_main')
    # ### end Alembic commands ###
