"""empty message

Revision ID: a6d10d1ea68a
Revises: 0723cfd6117c
Create Date: 2021-04-24 11:03:40.530934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6d10d1ea68a'
down_revision = '0723cfd6117c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raider', sa.Column('alt_id', sa.Integer(), nullable=True))
    op.add_column('raider', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.drop_constraint('raider_ibfk_1', 'raider', type_='foreignkey')
    op.create_foreign_key(None, 'raider', 'raider', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'raider', 'raider', ['alt_id'], ['id'])
    op.drop_column('raider', 'foreign_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raider', sa.Column('foreign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'raider', type_='foreignkey')
    op.drop_constraint(None, 'raider', type_='foreignkey')
    op.create_foreign_key('raider_ibfk_1', 'raider', 'raider', ['foreign_id'], ['id'])
    op.drop_column('raider', 'partner_id')
    op.drop_column('raider', 'alt_id')
    # ### end Alembic commands ###
