"""add realm and guild

Revision ID: c3c12f74b11e
Revises: 1b1263ed7d4b
Create Date: 2021-04-18 17:07:48.390495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c12f74b11e'
down_revision = '1b1263ed7d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('guild', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('realm', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'realm')
    op.drop_column('user', 'guild')
    # ### end Alembic commands ###
