"""empty message

Revision ID: d686f29465b4
Revises: b819e058c569
Create Date: 2021-04-23 21:45:54.602294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd686f29465b4'
down_revision = 'b819e058c569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('main_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['main_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'main_id')
    # ### end Alembic commands ###
