"""empty message

Revision ID: d7d0aff6de67
Revises: d686f29465b4
Create Date: 2021-04-24 10:30:47.209538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7d0aff6de67'
down_revision = 'd686f29465b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('raider', sa.Column('foreign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'raider', 'raider', ['foreign_id'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'main_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('main_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'user', ['main_id'], ['id'])
    op.drop_constraint(None, 'raider', type_='foreignkey')
    op.drop_column('raider', 'foreign_id')
    op.drop_table('profession')
    # ### end Alembic commands ###
